# Generated by Django 3.1.1 on 2020-10-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0004_image_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='img_after',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_after', to='histories.image'),
        ),
        migrations.AlterField(
            model_name='history',
            name='img_before',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_before', to='histories.image'),
        ),
    ]
